### ISSUE TITLE
cssparser-macros match_byte doctests fail

### ISSUE THREAD

**Issue by kalev** [servo/rust-cssparser#364] opened 2023-10-01 18:34 UTC
Latest git master:

```
$ cargo test
   Compiling cssparser-macros v0.6.1 (/home/kalev/tmp/rust-cssparser/macros)
    Finished test [unoptimized + debuginfo] target(s) in 0.34s
     Running unittests lib.rs (/home/kalev/tmp/rust-cssparser/target/debug/deps/cssparser_macros-7b5b4431cc393af6)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests cssparser-macros

running 1 test
test macros/lib.rs - match_byte (line 115) ... FAILED

failures:

---- macros/lib.rs - match_byte (line 115) stdout ----
error: cannot find macro `match_byte` in this scope
 --> macros/lib.rs:116:1
  |
3 | match_byte! { tokenizer.next_byte_unchecked(),
  | ^^^^^^^^^^
  |
help: consider importing this macro
  |
2 + use cssparser_macros::match_byte;
  |

error: aborting due to previous error

Couldn't compile the test.

failures:
    macros/lib.rs - match_byte (line 115)

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.04s

error: doctest failed, to rerun pass `--doc`
```

**Comment by tiaanl** [comment] 2024-03-22 13:24
I can't repro this and it looks like there were changes to `match_byte` here: #337.

I'm closing this for now, but feel free to reopen if the problem is still here.

**Closed by tiaanl** 2024-03-22 13:24 UTC
